import '@testing-library/jest-dom';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import { expect, afterEach, vi } from 'vitest';
import { cleanup } from '@testing-library/react';
import enAdmin from './src/i18n/locales/en/admin.json';

class TestResizeObserver {
  observe() {}
  unobserve() {}
  disconnect() {}
}

vi.stubGlobal('ResizeObserver', TestResizeObserver);

// cmdk keeps the active option visible. JSDOM does not implement this browser
// API, so command menus with initial suggestions need a no-op test shim.
Object.defineProperty(Element.prototype, 'scrollIntoView', {
  configurable: true,
  value: () => {},
});

// Force UTC+7 timezone to match shared parser tests
process.env.TZ = 'Asia/Bangkok';

// Cleanup after each test
afterEach(() => {
  cleanup();
});

// Initialize i18n for tests — matches the structure in src/i18n/locales/
i18n.use(initReactI18next).init({
  lng: 'en',
  fallbackLng: 'en',
  resources: {
    en: {
      admin: enAdmin,
      common: {
        app: { title: 'Mindoist' },
        language: { en: 'EN', vi: 'VI' },
        sync: { title: 'Sync center', description: 'See what is waiting and retry when a sync needs attention.', status: 'Status', synced: 'Synced', syncing: 'Syncing…', offline: 'Offline', error: 'Sync needs attention', pending: '{{count}} waiting', pendingLabel: 'Changes waiting', lastSynced: 'Last synced', never: 'Not yet', retry: 'Sync now', close: 'Close sync center' },
        appearance: {
          label: 'Appearance', accent: 'Accent color', chooseAccent: 'Choose an accent color',
          currentAccent: 'Accent color (currently {{accent}})',
          colors: { slate: 'Slate', indigo: 'Indigo', ocean: 'Ocean', violet: 'Violet', sky: 'Sky', jade: 'Jade', lime: 'Lime', rose: 'Rose', amber: 'Amber' },
        },
      },
      auth: {
        login: 'Login',
        register: 'Register',
        email: 'Email',
        password: 'Password',
        name: 'Name',
        confirm_password: 'Confirm Password',
        no_account: 'No account?',
        has_account: 'Already have an account?',
        error_password_mismatch: 'Passwords do not match',
        error_min_password: 'Password must be at least 6 characters',
        error_required: 'This field is required',
        logout: 'Logout',
        onboarding: {
          eyebrow: 'Your workspace',
          sideTitle: 'A calmer way to move work forward.',
          sideDescription: 'Set the essentials once.',
          progressLabel: 'Account setup progress',
          privateNote: 'Your profile details stay with your account.',
          stepCount: 'Step {{current}} of 3',
          continue: 'Continue',
          back: 'Back',
          finishing: 'Finishing setup...',
          error: "We couldn't finish setup. Check your connection and try again.",
          steps: {
            profile: 'Your details',
            intro: 'How it works',
            password: 'Backup sign-in',
          },
          profile: {
            title: 'Make this workspace yours',
            description: 'Confirm your details.',
            timeZone: 'Time zone',
            timeZoneHelp: 'This controls today, due dates, and reminders.',
          },
          intro: {
            title: 'From capture to a clear day',
            description: 'Three simple places keep work clear.',
            captureTitle: 'Capture without sorting first',
            captureBody: 'Send new thoughts to Inbox.',
            planTitle: 'Plan the day you can actually do',
            planBody: 'Use My Day and Calendar.',
            focusTitle: 'Finish with the details nearby',
            focusBody: 'Keep details attached to the work.',
          },
          password: {
            title: 'Add a backup way to sign in',
            description: 'Google sign-in will keep working.',
            newPassword: 'New password',
            help: 'Use at least 6 characters.',
            show: 'Show password',
            hide: 'Hide password',
            skip: 'Skip for now',
            create: 'Create password and start',
          },
        },
      },
      tasks: {
 sidebar: { summary: 'Summary', review: 'Review', inbox: 'Inbox', today: 'Today', next7: 'Next 7 Days', projects: 'Projects', tags: 'Tags', overdue: 'Overdue', completed: 'Completed', notes: 'Notes', calendar: 'Calendar', countdown: 'Countdown', import: 'Import', settings: 'Settings', admin: 'Admin Console', more: 'More' },
        projects: {
          addProject: 'Add project', addSubproject: 'Add a sub-project to {{name}}', newProject: 'New project', newSubproject: 'New sub-project', namePlaceholder: 'Project name', create: 'Create', creating: 'Creating…', cancel: 'Cancel', createError: "Couldn't create this project. Try again.",
          projectEyebrow: 'New workspace', subprojectEyebrow: 'New sub-project', createProjectTitle: 'Create a project', createSubprojectTitle: 'Add to {{name}}', name: 'Project name', dailyNamePlaceholder: 'What are you logging today?', chooseTemplate: 'Choose a workflow', customColumns: 'Custom columns', customColumnsPlaceholder: 'Ideas, Doing, Done', customColumnsHint: 'Separate column names with commas.', color: 'Project color',
          templates: { DAILY_LOG: { name: 'Daily Log', description: "A dated board for today's flow" }, JOB: { name: 'Job Search', description: 'Track every application stage' }, PERSONAL: { name: 'Personal', description: 'Plan from backlog to today' }, CUSTOM: { name: 'Custom', description: 'Build your own workflow' } },
          colors: { indigo: 'Indigo', ocean: 'Ocean', jade: 'Jade', rose: 'Rose', amber: 'Amber' },
        },
        tags: { addTag: 'Add tag', namePlaceholder: 'Tag name', empty: 'No tags yet. Create one above.', createError: "Couldn't create this tag. Try again.", manageTags: 'Manage tags', manageHint: 'Create, assign, or delete tags.', deleteTag: 'Delete tag {{name}}', deleteConfirm: 'Delete #{{name}}? It will be removed from every task.', delete: 'Delete tag', cancel: 'Cancel', deleteError: "Couldn't delete this tag. Try again." },
        workspace: { eyebrow: 'Project workspace', subtitle_one: '{{count}} task across your workflow', subtitle_other: '{{count}} tasks across your workflow', loading: 'Loading project workspace', viewMode: 'Workspace view', board: 'Board', list: 'List', addColumn: 'Add column', newColumn: 'New column', columnName: 'Column name', columnColor: 'Column color', columnColors: { slate: 'Slate', ocean: 'Ocean', jade: 'Jade', amber: 'Amber', rose: 'Rose', indigo: 'Indigo' }, add: 'Add', saveColumn: 'Save column name', renameColumn: 'Rename {{name}}', deleteColumn: 'Delete {{name}}', deleteConfirm: 'Delete “{{name}}”? Its tasks will return to the first column.', delete: 'Delete', markDone: 'Mark as a completion column', unmarkDone: 'Remove completion status', emptyColumn: 'Drop tasks here', moveTo: 'Move to', moveTask: 'Move {{title}} to another column', dragHint: 'Drag cards between columns, or use the Move to menu for keyboard access.', moveError: "Couldn't move this task. Try again.", columnError: "Couldn't save this column. Try again.", deleteError: "Couldn't delete this column. A project must keep at least one column.", deleteProject: 'Delete project', deleteProjectConfirm: 'Delete “{{name}}”? Its tasks will remain, but won\'t be grouped under this project anymore.', deleteProjectError: "Couldn't delete this project. Try again.", renameProject: 'Rename {{name}}', projectName: 'Project name', saveProjectName: 'Save project name', projectRenameError: "Couldn't rename this project. Try again.", calendarSyncOn: 'Calendar sync on', calendarSyncOff: 'Calendar sync off', calendarSyncError: 'Unable to update calendar sync', cancel: 'Cancel' },
        bottomNav: { label: 'Primary navigation' },
        list: {
          empty: 'No tasks yet', addPlaceholder: 'Add a task...', completed: 'Completed', reopen: 'Reopen',
          searchPlaceholder: 'Search tasks...', noResults: 'No tasks found', retry: 'Retry',
          selectVisible: 'Select visible', selectTask: 'Select {{title}}', selectedCount: '{{count}} selected',
          bulkComplete: 'Complete', bulkDelete: 'Delete', clearSelection: 'Clear selection',
        },
        undo: {
          action: 'Undo', dismiss: 'Dismiss notification', completed: 'Completed “{{title}}”', deleted: 'Deleted “{{title}}”',
          bulkCompleted: 'Completed {{count}} tasks', bulkDeleted: 'Deleted {{count}} tasks', failed: "Couldn't undo. Try again.",
        },
        detail: {
          loading: 'Loading task details',
          title: 'Task Details', editTitle: 'Edit Title', description: 'Description', close: 'Close', clear: 'Clear', duration: 'Duration',
          dueDate: 'Due Date', completionTime: 'Completion time', dueDay: 'Due day', timeline: 'Timeline',
          startDate: 'From', deadline: 'Deadline', deadlineTime: 'Deadline time',
          plannedTime: 'Planned time', addPlannedTime: 'Add time block', editPlannedTime: 'Edit {{range}}',
          removePlannedTime: 'Remove {{range}}', plannedDate: 'Date', plannedStart: 'Start', plannedEnd: 'End',
          savePlannedTime: 'Save time block', cancelPlannedTime: 'Cancel editing time block',
          plannedTimeLoading: 'Loading time blocks...', plannedTimeInvalid: 'End time must be after start time.',
          plannedTimeSaveError: "Couldn't save this time block. Try again.", plannedTimeLoadError: "Couldn't load planned time.",
          priority: 'Priority', project: 'Project', save: 'Save', cancel: 'Cancel', delete: 'Delete',
          noTags: 'Tags',
          color: 'Task color',
          noColor: 'Follow project color',
          colors: { slate: 'Slate', indigo: 'Indigo', violet: 'Violet', sky: 'Sky', jade: 'Jade', lime: 'Lime', amber: 'Amber', rose: 'Rose' },
        },
        pomodoro: {
          title: 'Focus timer', start: 'Start', pause: 'Pause', reset: 'Reset',
          workTime: 'Focus time', breakTime: 'Break time', completed: 'Session completed',
          sessions: '{{count}} sessions', running: 'Running', paused: 'Paused',
          error: "Couldn't save this focus session. Try again.",
        },
        dueCountdown: {
          remaining: 'Due in {{duration}}',
          overdue: '{{duration}} overdue',
          daysHours: '{{days}}d {{hours}}h',
          hoursMinutes: '{{hours}}h {{minutes}}m',
          minutes: '{{minutes}}m',
        },
        quickAdd: {
          add: 'Add task',
          placeholder: 'Add a task... (e.g., "buy milk tomorrow 9am p1")',
          preview: 'Preview',
          dueDate: 'Due date',
          dueTime: 'Due time',
          priority: 'Priority',
          before: 'before',
          dismiss: 'Dismiss preview',
            togglePreview: 'Toggle preview',
            globalCapture: 'Quick capture',
            command: {
              placeholder: 'Type a task or command…',
              mode: { create: 'Create', action: 'Actions', navigate: 'Navigate', search: 'Search' },
              inView: 'in {{view}}', selected: 'Selected: {{title}}', shortcuts: 'Start here',
              emptyTitle: 'Write it the way you think it', emptyDescription: 'Try “buy milk tomorrow at 9am p1” and Mindoist will structure it for you.',
              actions: 'Task actions', actionsHint: 'Complete, schedule, move or tag the selected task',
              navigate: 'Go somewhere', navigateHint: 'Open a view or project', search: 'Find a task', searchHint: 'Search titles and descriptions',
              noResults: 'No matching results. Try a shorter phrase.', createTask: 'Create task', createNamed: 'Create “{{title}}”',
              actionsFor: 'Actions for {{title}}', completeTask: 'Complete task', scheduleTask: 'Schedule in Calendar',
              moveTo: 'Move to {{project}}', tagWith: 'Tag with {{tag}}', selectFirst: 'Select a task before running task actions.',
              projects: 'Projects', tasks: 'Tasks', minutes: 'min', planTask: 'Plan', project: 'Project', noProject: 'No project', date: 'Date', time: 'Time', today: 'Today', tomorrow: 'Tomorrow', priority: 'Priority', noPriority: 'No priority', text: 'text', close: 'Close',
            },
            reminderFailed: 'Created “{{title}}”, but the reminder could not be saved. Try adding the reminder again.',
        },
        toggleSidebar: 'Toggle sidebar',
        completedView: {
          title: 'Completed',
          empty: 'No completed tasks yet',
          reopen: 'Reopen',
          today: 'Today',
          yesterday: 'Yesterday',
          dateGroup: '{{date}}',
        },
          calendar: {
            today: 'Today', daysShort: 'days', past: 'Past', month: 'Month', week: 'Week', day: 'Day', allDay: 'All day',
            dayCount_one: '{{count}} day', dayCount_other: '{{count}} days',
            noEvents: 'No tasks on this day', createTask: 'Create task', createEyebrow: 'New calendar task',
            taskTitle: 'Task title', taskTitlePlaceholder: 'What needs to happen?',
            selectedSlot: '{{date}}', selectedSlotWithTime: '{{date}} at {{time}}',
            selectedSlotWithRange: '{{date}} · {{startTime}} → {{endTime}}',
            creatingTask: 'Creating...', cancelCreate: 'Cancel', createError: "Couldn't create this task. Try again.",
            priorityLegend: 'Priority',
          priority1: 'P1 Urgent', priority2: 'P2 High', priority3: 'P3 Medium', priority4: 'P4 Low',
          google: 'Google Calendar', taskTooltip: '{{title}} · P{{priority}} · {{deadline}}',
          quickCreateLabel: 'Task name', quickCreatePlaceholder: 'What will you work on?…', quickCreateSave: 'Create scheduled task', quickCreateCancel: 'Cancel scheduled task', quickCreateProject: 'Project', quickCreateNoProject: 'No project', quickCreateColor: 'Task color', quickCreateInheritColor: 'Follow project color', quickCreateError: 'Could not create this scheduled task. Check your connection and try again.',
          timelineHint: 'Switch to Week or Day for a time-blocked view. Drag to reschedule; select a slot to add.',
          previousPeriod: 'Previous', nextPeriod: 'Next', viewSwitcher: 'Calendar view', hasNote: 'Has a note',
          planningPanel: 'Daily planner', planningPanelHint: 'Drag tasks onto the calendar, focus one block, then close the day.',
          panelToday: 'Today', panelOverdue: 'Overdue', panelBacklog: 'Backlog',
          panelEmptyToday: 'No tasks due today', panelEmptyOverdue: 'No overdue tasks',
          panelEmptyBacklog: 'No unscheduled tasks',
          ceremony: {
            label: 'Daily planning modes', tabs: { plan: 'Plan', focus: 'Focus', shutdown: 'Close day' },
            timeBlocked: 'Time blocked', remainingCapacity: 'Remaining capacity', unscheduled: 'Unscheduled',
            overcommitted: 'Overcommitted by {{duration}}. Move or shorten a block.', currentBlock: 'Current block', nextBlock: 'Next block',
            scheduledTask: 'Scheduled task', focusBlock: 'Focus block', actualMinutes: '{{count}}m actual', start: 'Start', pause: 'Pause', complete: 'Complete',
            noFocusBlock: 'No current or upcoming block today.', plannedActual: 'Planned / actual', slippedTasks: 'Slipped tasks',
            moveAllTomorrow: 'Move all to tomorrow', moveTomorrow: 'Move tomorrow · {{title}}', cleanShutdown: 'Day closed cleanly. Nothing slipped.',
          },
        },
        summary: {
          eyebrow: 'Your momentum', title: 'Summary', subtitle: 'A clear view of what is moving and what needs attention.',
          projectFilter: 'Filter by project', allProjects: 'All projects', noProject: 'No project', unknownProject: 'Unknown project',
          total: 'Total tasks', open: 'Open', completed: 'Completed', completedThisWeek: 'This week', overdue: 'Overdue', trend: 'Completion trend',
          plannedActual: 'Planned vs actual', plannedActualDescription: 'Compare planned and actual time.', plannedActualLoadFailed: 'Unable to load planned and actual time.',
          plannedTime: 'Planned', actualTime: 'Actual', variance: 'Variance', slippedBlocks: 'Slipped blocks', blocksCompleted: '{{completed}}/{{total}} blocks completed', actualProgress: 'Actual time is {{progress}}% of planned time',
          trendDescription: 'Tasks completed each day', range: 'Trend period', days: '{{count}} days',
          trendAria: 'Completed tasks over the last {{days}} days', dayCompleted: '{{date}}: {{count}} completed',
          byPriority: 'Tasks by priority', byProject: 'Tasks by project', emptyTitle: 'Your summary will grow with your tasks',
          emptyDescription: 'Add and complete a few tasks to see priorities, projects, and momentum here.', loading: 'Loading summary',
          calendarOverview: 'Calendar overview', calendarDescription: 'Select a date to see its tasks',
          monthView: 'Monthly view', periodView: 'Summary period', calendarView: 'Calendar', weeklyList: 'Week', monthlyList: 'Monthly list',
          weeklyListDescription: 'Review Monday through Sunday as one continuous task ledger',
          monthlyListDescription: 'Review the month as one continuous task ledger', monthlyStats: 'Monthly task totals', weeklyStats: 'Weekly task totals',
          weekRange: '{{start}} – {{end}}',
          monthTotal: 'Total', monthCompleted: 'Completed', monthOpen: 'Open', monthOverdue: 'Overdue',
          noTasksForMonth: 'No task activity in this month', noTasksForWeek: 'No task activity in this week', openTask: 'Open {{title}}', due: 'Due', dueAt: 'Due {{time}}', added: 'Added',
          openObsidian: 'Send to Obsidian', obsidianOpening: 'Preparing note…',
          obsidianHint: 'Creates a Markdown note in Obsidian. No plugin required.',
          obsidianNeedsSetup: 'Choose your local vault and destination folder before sending this monthly note.',
          obsidianDestination: 'Destination: {{vault}} / {{path}}', configureObsidian: 'Configure Obsidian',
          obsidianReady: 'The Markdown is ready and Obsidian is opening.', obsidianError: "Couldn't open Obsidian.",
          obsidianNoteName: 'Mindoist Monthly Review {{month}}', obsidianNoteTitle: 'Mindoist monthly review — {{month}}',
          obsidianWeeklyNoteTitle: 'Mindoist weekly review — {{range}}',
          monthlyDigest: '{{total}} tasks · {{completed}} completed · {{open}} open · {{overdue}} overdue', weeklyDigest: '{{total}} tasks this week · {{completed}} completed · {{open}} open · {{overdue}} overdue',
          previewMarkdown: 'Preview Markdown', hideMarkdown: 'Hide preview', markdownPreviewTitle: 'Obsidian Markdown template',
          markdownPreviewHint: 'This is the exact frontmatter and checkbox content prepared for the selected period.', copyMarkdown: 'Copy Markdown',
          markdownCopied: 'Markdown copied.', markdownCopyError: "Couldn't copy Markdown.", previousWeek: 'Previous week', nextWeek: 'Next week',
          previousMonth: 'Previous month', nextMonth: 'Next month', calendarDay_one: '{{date}}, {{count}} task',
          calendarDay_other: '{{date}}, {{count}} tasks', taskCount_one: '{{count}} task', taskCount_other: '{{count}} tasks',
          noTasksForDate: 'No tasks scheduled for this day',
        },
        repeatBadge: 'Recurring',
        settingsPage: {
          title: 'Settings', account: 'Account', appearance: 'Appearance', navigation: 'Navigation', integrations: 'Integrations', google: 'Google', data: 'Data', about: 'About',
          integrationsHint: 'Connect trusted services to your Mindoist account.',
          obsidianTitle: 'Obsidian', obsidianDescription: 'Send each monthly summary to a Markdown note in your local vault without installing a plugin.',
          obsidianConfigured: 'Configured', obsidianNotConfigured: 'Not configured',
          obsidianVault: 'Vault name or ID', obsidianVaultHint: 'Use the vault name shown in Obsidian, such as “Hiếu - Personal”, or its 16-character vault ID.',
          obsidianFolder: 'Folder inside the vault', obsidianFolderHint: 'Use a path relative to the vault root. Leave blank to use the default note location.',
          obsidianFilename: 'Monthly note name', obsidianFilenameHint: 'Keep {{monthToken}} in the name so each month gets a separate note.',
          obsidianWeeklyFilename: 'Weekly note name', obsidianWeeklyFilenameHint: 'Keep {{weekToken}} in the name so each week gets a separate note.',
          obsidianPreview: 'Destination preview', obsidianMonthlyShort: 'Monthly', obsidianWeeklyShort: 'Weekly', obsidianVaultPlaceholder: 'Your vault',
          obsidianLocalOnly: 'This configuration is saved only in this browser for your signed-in Mindoist account.',
          obsidianOpenVault: 'Open vault', obsidianSave: 'Save Obsidian settings', obsidianSaved: 'Saved',
          obsidianErrors: {
            vaultRequired: 'Enter an Obsidian vault name or ID.', folderInvalid: 'Use a folder path inside the vault without .. or invalid filename characters.',
            filenameRequired: 'Enter a monthly note name.', filenameMonthRequired: 'Include {{monthToken}} so notes from different months do not collide.',
            filenameInvalid: 'The note name cannot contain slashes or invalid filename characters.',
            weeklyFilenameRequired: 'Enter a weekly note name.', weeklyFilenameWeekRequired: 'Include {{weekToken}} so notes from different weeks do not collide.',
            weeklyFilenameInvalid: 'The weekly note name cannot contain slashes or invalid filename characters.',
          },
          theme: 'Theme', language: 'Language', googleCalendar: 'Google Calendar',
          password: 'Password', passwordHint: 'Set or change the password for email login.',
          newPassword: 'New password', confirmPassword: 'Confirm password', savePassword: 'Save password',
          passwordMinError: 'Password must be at least 6 characters.',
          passwordMismatch: 'Passwords do not match.', passwordSaved: 'Password saved.',
          googleCalendarHint: 'Sync tasks with due dates to your Google Calendar.',
          importTitle: 'Import data', importHint: 'Bring in tasks from another app or a CSV file.',
          productivity: 'Productivity',
          notifications: 'Task reminders',
          notificationsHint: 'Allow browser notifications so reminders can appear when they are due.',
          notificationsUnsupported: 'This browser or app mode does not support push notifications.',
          notificationsDenied: 'Notifications are blocked in the browser. Enable them in site settings to use reminders.',
          notificationsError: "Couldn't update notifications. Try again.",
          pomodoroWorkMinutes: 'Focus duration',
          pomodoroBreakMinutes: 'Break duration',
          pomodoroWorkMinutesHint: 'Minutes per focus session (1–120)',
          pomodoroBreakMinutesHint: 'Minutes per break (1–60)',
          workHoursPerDay: 'Work hours per day',
          workHoursPerDayHint: 'Used by the Today planning progress bar (1–24)',
          telegramBot: 'Mindoist on Telegram', telegramHint: 'Use the shared Mindoist bot.',
          telegramConnected: 'Connected', telegramPending: 'Waiting for confirmation',
          telegramLoading: 'Checking Telegram connection…', telegramUnavailable: 'Telegram is not configured.',
          telegramUnlinked: 'Connect your Telegram account to continue.',
          telegramPendingHint: 'Open the bot and press Start to confirm this account.',
          telegramExpires: 'This link expires at {{time}}.', telegramAccount: 'Telegram account',
          telegramLinkedAt: 'Linked {{date}}', telegramConnect: 'Connect Telegram',
          telegramCreating: 'Creating link…', telegramNewLink: 'Create new link', telegramOpen: 'Open Telegram',
          telegramDisconnect: 'Disconnect', telegramDisconnecting: 'Disconnecting…',
          telegramDisconnectConfirm: 'Disconnect Telegram?', telegramLoadError: "Couldn't check Telegram.", telegramRetry: 'Try again',
          telegramConnectError: "Couldn't create a Telegram link.", telegramDisconnectError: "Couldn't disconnect Telegram.",
          telegramGuideTitle: 'How to use Mindoist on Telegram', telegramGuideHint: 'Write naturally.',
          telegramGuideStep1Title: 'Connect once', telegramGuideStep1Text: 'Open the bot and press Start.',
          telegramGuideStep2Title: 'Send your request', telegramGuideStep2Text: 'Include the details you need.',
          telegramGuideStep3Title: 'Review the draft', telegramGuideStep3Text: 'Reply confirm, edit, or cancel.',
          telegramGuideGoalColumn: 'What you want', telegramGuideMessageColumn: 'Example message',
          telegramGuideCreateLabel: 'Create a task', telegramGuideCreateExample: 'Create task “Renew domain” in project Work',
          telegramGuideBatchLabel: 'Create multiple tasks', telegramGuideBatchExample: 'Create tag #Infrastructure, then create: 1. Check DNS; 2. Renew SSL',
          telegramGuideTodayLabel: 'View a day', telegramGuideTodayExample: 'What tasks do I have today?',
          telegramGuideStatsLabel: 'Get a summary', telegramGuideStatsExample: 'Summarize my tasks this week',
          telegramGuideReviseLabel: 'Edit or cancel', telegramGuideReviseExample: 'edit the due time to 14:00 · cancel',
          telegramGuideNote: 'Use the exact project and tag names already in Mindoist. For task creation, nothing is saved until you reply confirm.',
        },
        notificationPrompt: {
          title: 'Turn on reminders?',
          description: 'Mindoist can notify you when tasks and countdowns reach their due time.',
          enable: 'Enable notifications',
          enabling: 'Enabling…',
          later: 'Later',
          dismiss: 'Dismiss notification prompt',
          error: "Couldn't enable notifications. Try again.",
        },
        countdown: {
          add: 'Add countdown', title: 'Title', titlePlaceholder: 'Birthday, anniversary, deadline...',
          date: 'Date', time: 'Time (optional)', color: 'Color', save: 'Save', delete: 'Delete countdown',
          empty: 'No countdowns yet — add a date worth counting down to.',
          daysLeft: 'days left', daysAgo: 'days ago',
          reminder: 'Reminder', reminderNone: 'On the day only',
          reminderDays_one: '{{count}} day early', reminderDays_other: '{{count}} days early',
          showInCalendar: 'Show in Calendar',
          showInCalendarHint: 'Also show this countdown as an event on its date in Calendar.',
        },
      },
    },
    vi: {
      common: {
        app: { title: 'Mindoist' },
        language: { en: 'EN', vi: 'VI' },
        sync: { title: 'Trung tâm đồng bộ', description: 'Xem thay đổi đang chờ và thử lại khi đồng bộ gặp lỗi.', status: 'Trạng thái', synced: 'Đã đồng bộ', syncing: 'Đang đồng bộ…', offline: 'Ngoại tuyến', error: 'Đồng bộ cần xử lý', pending: '{{count}} thay đổi đang chờ', pendingLabel: 'Thay đổi đang chờ', lastSynced: 'Đồng bộ lần cuối', never: 'Chưa có', retry: 'Đồng bộ ngay', close: 'Đóng trung tâm đồng bộ' },
        appearance: {
          label: 'Giao diện', accent: 'Màu chủ đạo', chooseAccent: 'Chọn màu chủ đạo',
          currentAccent: 'Màu chủ đạo (hiện tại {{accent}})',
          colors: { indigo: 'Chàm', ocean: 'Đại dương', jade: 'Ngọc bích', rose: 'Hồng', amber: 'Hổ phách' },
        },
      },
      auth: {
        login: 'Đăng nhập',
        register: 'Đăng ký',
        email: 'Email',
        password: 'Mật khẩu',
        name: 'Tên',
        confirm_password: 'Xác nhận mật khẩu',
        no_account: 'Chưa có tài khoản?',
        has_account: 'Đã có tài khoản?',
        error_password_mismatch: 'Mật khẩu không khớp',
        error_min_password: 'Mật khẩu phải ít nhất 6 ký tự',
        error_required: 'Trường này là bắt buộc',
        logout: 'Đăng xuất',
        onboarding: {
          eyebrow: 'Không gian của bạn',
          sideTitle: 'Một cách nhẹ nhàng hơn để hoàn thành công việc.',
          sideDescription: 'Thiết lập thông tin cần thiết một lần.',
          progressLabel: 'Tiến trình thiết lập tài khoản',
          privateNote: 'Thông tin hồ sơ được lưu trong tài khoản của bạn.',
          stepCount: 'Bước {{current}} / 3',
          continue: 'Tiếp tục',
          back: 'Quay lại',
          finishing: 'Đang hoàn tất...',
          error: 'Chưa thể hoàn tất thiết lập.',
          steps: {
            profile: 'Thông tin của bạn',
            intro: 'Cách hoạt động',
            password: 'Đăng nhập dự phòng',
          },
          profile: {
            title: 'Biến đây thành không gian của bạn',
            description: 'Xác nhận thông tin của bạn.',
            timeZone: 'Múi giờ',
            timeZoneHelp: 'Múi giờ quyết định ngày và lời nhắc.',
          },
          intro: {
            title: 'Từ ghi nhanh đến một ngày rõ ràng',
            description: 'Ba nơi đơn giản giúp công việc rõ ràng.',
            captureTitle: 'Ghi lại trước, sắp xếp sau',
            captureBody: 'Đưa ý tưởng mới vào Inbox.',
            planTitle: 'Lên kế hoạch vừa sức',
            planBody: 'Dùng Ngày của tôi và Lịch.',
            focusTitle: 'Hoàn thành với đủ thông tin',
            focusBody: 'Giữ thông tin bên cạnh công việc.',
          },
          password: {
            title: 'Thêm một cách đăng nhập dự phòng',
            description: 'Đăng nhập Google vẫn hoạt động.',
            newPassword: 'Mật khẩu mới',
            help: 'Dùng ít nhất 6 ký tự.',
            show: 'Hiện mật khẩu',
            hide: 'Ẩn mật khẩu',
            skip: 'Để sau',
            create: 'Tạo mật khẩu và bắt đầu',
          },
        },
      },
      tasks: {
 sidebar: { summary: 'Tổng quan', review: 'Tổng kết', inbox: 'Hộp thư', today: 'Hôm nay', next7: '7 ngày tới', projects: 'Dự án', tags: 'Thẻ', overdue: 'Quá hạn', completed: 'Đã hoàn thành', notes: 'Ghi chú', calendar: 'Lịch', countdown: 'Đếm ngày', import: 'Nhập dữ liệu', settings: 'Cài đặt', admin: 'Quản trị', more: 'Khác' },
        projects: {
          addProject: 'Thêm dự án', addSubproject: 'Thêm dự án con vào {{name}}', newProject: 'Dự án mới', newSubproject: 'Dự án con mới', namePlaceholder: 'Tên dự án', create: 'Tạo', creating: 'Đang tạo…', cancel: 'Hủy', createError: 'Không thể tạo dự án. Hãy thử lại.',
          projectEyebrow: 'Không gian mới', subprojectEyebrow: 'Dự án con mới', createProjectTitle: 'Tạo dự án', createSubprojectTitle: 'Thêm vào {{name}}', name: 'Tên dự án', dailyNamePlaceholder: 'Hôm nay bạn muốn ghi lại điều gì?', chooseTemplate: 'Chọn quy trình', customColumns: 'Các cột tùy chỉnh', customColumnsPlaceholder: 'Ý tưởng, Đang làm, Hoàn thành', customColumnsHint: 'Ngăn cách tên cột bằng dấu phẩy.', color: 'Màu dự án',
          templates: { DAILY_LOG: { name: 'Nhật ký ngày', description: 'Bảng theo ngày' }, JOB: { name: 'Tìm việc', description: 'Theo dõi từng vòng ứng tuyển' }, PERSONAL: { name: 'Cá nhân', description: 'Lên kế hoạch cá nhân' }, CUSTOM: { name: 'Tùy chỉnh', description: 'Tự xây dựng quy trình riêng' } },
          colors: { indigo: 'Chàm', ocean: 'Đại dương', jade: 'Ngọc bích', rose: 'Hồng', amber: 'Hổ phách' },
        },
        tags: { addTag: 'Thêm thẻ', namePlaceholder: 'Tên thẻ', empty: 'Chưa có thẻ. Tạo thẻ mới ở trên.', createError: 'Chưa tạo được thẻ này. Thử lại nhé.', manageTags: 'Quản lý thẻ', manageHint: 'Tạo, gắn hoặc xóa thẻ.', deleteTag: 'Xóa thẻ {{name}}', deleteConfirm: 'Xóa #{{name}}? Thẻ sẽ bị gỡ khỏi mọi task.', delete: 'Xóa thẻ', cancel: 'Hủy', deleteError: 'Chưa xóa được thẻ này. Thử lại nhé.' },
        workspace: { eyebrow: 'Không gian dự án', subtitle: '{{count}} task trong quy trình của bạn', loading: 'Đang tải không gian dự án', viewMode: 'Kiểu hiển thị', board: 'Bảng', list: 'Danh sách', addColumn: 'Thêm cột', newColumn: 'Cột mới', columnName: 'Tên cột', columnColor: 'Màu cột', columnColors: { slate: 'Xám đá', ocean: 'Đại dương', jade: 'Ngọc bích', amber: 'Hổ phách', rose: 'Hồng', indigo: 'Chàm' }, add: 'Thêm', saveColumn: 'Lưu tên cột', renameColumn: 'Đổi tên {{name}}', deleteColumn: 'Xóa {{name}}', deleteConfirm: 'Xóa “{{name}}”? Các task sẽ trở về cột đầu tiên.', delete: 'Xóa', markDone: 'Đánh dấu là cột hoàn thành', unmarkDone: 'Bỏ trạng thái hoàn thành', emptyColumn: 'Thả task vào đây', moveTo: 'Chuyển đến', moveTask: 'Chuyển {{title}} sang cột khác', dragHint: 'Kéo thẻ giữa các cột, hoặc dùng menu Chuyển đến khi thao tác bằng bàn phím.', moveError: 'Không thể chuyển task. Hãy thử lại.', columnError: 'Không thể lưu cột. Hãy thử lại.', deleteError: 'Không thể xóa cột. Dự án phải giữ ít nhất một cột.', deleteProject: 'Xóa dự án', deleteProjectConfirm: 'Xóa “{{name}}”? Các task bên trong vẫn còn, nhưng sẽ không thuộc dự án này nữa.', deleteProjectError: 'Không thể xóa dự án. Hãy thử lại.', renameProject: 'Đổi tên {{name}}', projectName: 'Tên dự án', saveProjectName: 'Lưu tên dự án', projectRenameError: 'Không thể đổi tên dự án. Hãy thử lại.', calendarSyncOn: 'Đang đồng bộ lịch', calendarSyncOff: 'Chưa đồng bộ lịch', calendarSyncError: 'Không thể cập nhật đồng bộ lịch', cancel: 'Hủy' },
        bottomNav: { label: 'Điều hướng chính' },
        list: {
          empty: 'Chưa có task nào', addPlaceholder: 'Thêm task...', completed: 'Hoàn thành', reopen: 'Mở lại',
          searchPlaceholder: 'Tìm kiếm task...', noResults: 'Không tìm thấy task', retry: 'Thử lại',
          selectVisible: 'Chọn các task đang hiện', selectTask: 'Chọn {{title}}', selectedCount: 'Đã chọn {{count}}',
          bulkComplete: 'Hoàn thành', bulkDelete: 'Xóa', clearSelection: 'Bỏ chọn',
        },
        undo: {
          action: 'Hoàn tác', dismiss: 'Đóng thông báo', completed: 'Đã hoàn thành “{{title}}”', deleted: 'Đã xóa “{{title}}”',
          bulkCompleted: 'Đã hoàn thành {{count}} task', bulkDeleted: 'Đã xóa {{count}} task', failed: 'Không thể hoàn tác. Hãy thử lại.',
        },
        detail: {
          loading: 'Đang tải chi tiết task',
          title: 'Chi tiết task', editTitle: 'Sửa tiêu đề', description: 'Mô tả', close: 'Đóng', clear: 'Xoá', duration: 'Thời lượng',
          dueDate: 'Ngày hết hạn', completionTime: 'Thời gian hoàn thành', dueDay: 'Due day', timeline: 'Timeline',
          startDate: 'Từ ngày', deadline: 'Deadline', deadlineTime: 'Giờ Deadline',
          plannedTime: 'Khung giờ làm', addPlannedTime: 'Thêm khung giờ', editPlannedTime: 'Sửa {{range}}',
          removePlannedTime: 'Xóa {{range}}', plannedDate: 'Ngày', plannedStart: 'Bắt đầu', plannedEnd: 'Kết thúc',
          savePlannedTime: 'Lưu khung giờ', cancelPlannedTime: 'Hủy sửa khung giờ',
          plannedTimeLoading: 'Đang tải khung giờ...', plannedTimeInvalid: 'Giờ kết thúc phải sau giờ bắt đầu.',
          plannedTimeSaveError: 'Chưa lưu được khung giờ. Thử lại nhé.', plannedTimeLoadError: 'Chưa tải được khung giờ làm.',
          priority: 'Ưu tiên', project: 'Dự án', save: 'Lưu', cancel: 'Hủy', delete: 'Xóa',
          noTags: 'Thẻ',
          color: 'Màu task',
          noColor: 'Theo màu dự án',
          colors: { slate: 'Xám đá', indigo: 'Chàm', violet: 'Tím', sky: 'Xanh trời', jade: 'Ngọc bích', lime: 'Xanh chanh', amber: 'Hổ phách', rose: 'Hồng' },
        },
        pomodoro: {
          title: 'Hẹn giờ tập trung', start: 'Bắt đầu', pause: 'Tạm dừng', reset: 'Đặt lại',
          workTime: 'Giờ tập trung', breakTime: 'Giờ nghỉ', completed: 'Đã hoàn thành phiên',
          sessions: '{{count}} phiên', running: 'Đang chạy', paused: 'Đã tạm dừng',
          error: 'Không thể lưu phiên tập trung. Hãy thử lại.',
        },
        dueCountdown: {
          remaining: 'Còn {{duration}}',
          overdue: 'Quá hạn {{duration}}',
          daysHours: '{{days}}n {{hours}}g',
          hoursMinutes: '{{hours}}g {{minutes}}p',
          minutes: '{{minutes}}p',
        },
        quickAdd: {
          add: 'Thêm task',
          placeholder: 'Thêm task... (vd: "mua sữa ngày mai 9h p1")',
          preview: 'Xem trước',
          dueDate: 'Ngày',
          dueTime: 'Giờ',
          priority: 'Ưu tiên',
          before: 'trước',
          dismiss: 'Bỏ xem trước',
            togglePreview: 'Ẩn/hiện xem trước',
            globalCapture: 'Thêm nhanh',
            command: {
              placeholder: 'Nhập task hoặc lệnh…',
              mode: { create: 'Tạo task', action: 'Thao tác', navigate: 'Đi tới', search: 'Tìm kiếm' },
              inView: 'trong {{view}}', selected: 'Đang chọn: {{title}}', shortcuts: 'Bắt đầu nhanh',
              emptyTitle: 'Cứ viết như cách bạn nghĩ', emptyDescription: 'Thử “mua sữa ngày mai lúc 9h p1”, Mindoist sẽ tự sắp xếp thông tin.',
              actions: 'Thao tác với task', actionsHint: 'Hoàn thành, lên lịch, di chuyển hoặc gắn tag',
              navigate: 'Đi tới một nơi', navigateHint: 'Mở nhanh một màn hình hoặc dự án', search: 'Tìm một task', searchHint: 'Tìm trong tiêu đề và mô tả',
              noResults: 'Không tìm thấy kết quả. Hãy thử cụm từ ngắn hơn.', createTask: 'Tạo task', createNamed: 'Tạo “{{title}}”',
              actionsFor: 'Thao tác với {{title}}', completeTask: 'Hoàn thành task', scheduleTask: 'Lên lịch trong Lịch',
              moveTo: 'Chuyển tới {{project}}', tagWith: 'Gắn tag {{tag}}', selectFirst: 'Hãy chọn một task trước khi chạy thao tác.',
              projects: 'Dự án', tasks: 'Task', minutes: 'phút', planTask: 'Xếp nhanh', project: 'Dự án', noProject: 'Không dự án', date: 'Ngày', time: 'Giờ', today: 'Hôm nay', tomorrow: 'Ngày mai', priority: 'Ưu tiên', noPriority: 'Không ưu tiên', text: 'nội dung', close: 'Đóng',
            },
            reminderFailed: 'Đã tạo “{{title}}”, nhưng chưa lưu được nhắc việc. Hãy thêm lại nhắc việc.',
        },
        toggleSidebar: 'Ẩn/hiện thanh bên',
        completedView: {
          title: 'Đã hoàn thành',
          empty: 'Chưa có task hoàn thành',
          reopen: 'Mở lại',
          today: 'Hôm nay',
          yesterday: 'Hôm qua',
          dateGroup: '{{date}}',
        },
          calendar: {
            today: 'Hôm nay', month: 'Tháng', week: 'Tuần', day: 'Ngày', allDay: 'Cả ngày',
            dayCount_one: '{{count}} ngày', dayCount_other: '{{count}} ngày',
            noEvents: 'Không có task ngày này', createTask: 'Tạo task', createEyebrow: 'Task lịch mới',
            taskTitle: 'Tên task', taskTitlePlaceholder: 'Cần làm gì?',
            selectedSlot: '{{date}}', selectedSlotWithTime: '{{date}} lúc {{time}}',
            selectedSlotWithRange: '{{date}} · {{startTime}} → {{endTime}}',
            creatingTask: 'Đang tạo...', cancelCreate: 'Hủy', createError: 'Chưa tạo được task này. Thử lại nhé.',
            priorityLegend: 'Ưu tiên',
          priority1: 'P1 Khẩn cấp', priority2: 'P2 Cao', priority3: 'P3 Trung bình', priority4: 'P4 Thấp',
          google: 'Lịch Google', taskTooltip: '{{title}} · P{{priority}} · {{deadline}}',
          quickCreateLabel: 'Tên task', quickCreatePlaceholder: 'Bạn sẽ làm việc gì?…', quickCreateSave: 'Tạo task theo lịch', quickCreateCancel: 'Hủy task theo lịch', quickCreateProject: 'Dự án', quickCreateNoProject: 'Không có dự án', quickCreateColor: 'Màu task', quickCreateInheritColor: 'Theo màu dự án', quickCreateError: 'Không tạo được task theo lịch. Hãy kiểm tra kết nối rồi thử lại.',
          timelineHint: 'Chuyển sang Tuần hoặc Ngày để xem theo khung giờ. Kéo để đổi lịch; chọn ô giờ để thêm.',
          previousPeriod: 'Trước', nextPeriod: 'Tiếp', viewSwitcher: 'Chế độ xem lịch', hasNote: 'Có ghi chú',
          planningPanel: 'Kế hoạch trong ngày', planningPanelHint: 'Kéo task vào lịch, tập trung theo từng phiên rồi chốt ngày.',
          panelToday: 'Hôm nay', panelOverdue: 'Quá hạn', panelBacklog: 'Chờ xử lý',
          panelEmptyToday: 'Không có task nào đến hạn hôm nay', panelEmptyOverdue: 'Không có task quá hạn',
          panelEmptyBacklog: 'Không có task chưa lên lịch',
          ceremony: {
            label: 'Các chế độ kế hoạch trong ngày', tabs: { plan: 'Kế hoạch', focus: 'Tập trung', shutdown: 'Chốt ngày' },
            timeBlocked: 'Thời gian đã xếp', remainingCapacity: 'Thời gian còn lại', unscheduled: 'Chưa xếp lịch',
            overcommitted: 'Đã vượt {{duration}}. Hãy dời hoặc rút ngắn một phiên.', currentBlock: 'Phiên hiện tại', nextBlock: 'Phiên tiếp theo',
            scheduledTask: 'Task đã xếp lịch', focusBlock: 'Phiên tập trung', actualMinutes: 'Đã làm {{count}} phút', start: 'Bắt đầu', pause: 'Tạm dừng', complete: 'Hoàn thành',
            noFocusBlock: 'Hôm nay không còn phiên hiện tại hoặc sắp tới.', plannedActual: 'Kế hoạch / thực tế', slippedTasks: 'Task bị trượt',
            moveAllTomorrow: 'Dời tất cả sang ngày mai', moveTomorrow: 'Dời sang mai · {{title}}', cleanShutdown: 'Đã chốt ngày. Không có task bị trượt.',
          },
        },
        summary: {
          eyebrow: 'Nhịp tiến độ', title: 'Tổng quan', subtitle: 'Nhìn nhanh việc đang tiến triển và việc cần chú ý.',
          projectFilter: 'Lọc theo dự án', allProjects: 'Tất cả dự án', noProject: 'Không có dự án', unknownProject: 'Dự án không xác định',
          total: 'Tổng task', open: 'Đang mở', completed: 'Hoàn thành', completedThisWeek: 'Tuần này', overdue: 'Quá hạn', trend: 'Xu hướng hoàn thành',
          plannedActual: 'Kế hoạch và thực tế', plannedActualDescription: 'So sánh thời gian kế hoạch và thực tế.', plannedActualLoadFailed: 'Không tải được thời gian kế hoạch và thực tế.',
          plannedTime: 'Kế hoạch', actualTime: 'Thực tế', variance: 'Chênh lệch', slippedBlocks: 'Khung giờ bị trượt', blocksCompleted: 'Hoàn tất {{completed}}/{{total}} khung giờ', actualProgress: 'Thời gian thực tế bằng {{progress}}% kế hoạch',
          trendDescription: 'Số task hoàn thành mỗi ngày', range: 'Khoảng thời gian', days: '{{count}} ngày',
          trendAria: 'Task hoàn thành trong {{days}} ngày gần nhất', dayCompleted: '{{date}}: hoàn thành {{count}} task',
          byPriority: 'Task theo ưu tiên', byProject: 'Task theo dự án', emptyTitle: 'Tổng quan sẽ đầy dần theo task của bạn',
          emptyDescription: 'Hãy thêm và hoàn thành vài task để xem ưu tiên, dự án và nhịp tiến độ tại đây.', loading: 'Đang tải tổng quan',
          calendarOverview: 'Tổng quan lịch', calendarDescription: 'Chọn một ngày để xem task',
          monthView: 'Chế độ xem theo tháng', periodView: 'Kỳ tổng kết', calendarView: 'Lịch', weeklyList: 'Tuần', monthlyList: 'Danh sách tháng',
          weeklyListDescription: 'Xem lại task từ Thứ Hai đến Chủ Nhật trong một danh sách liền mạch',
          monthlyListDescription: 'Xem lại cả tháng trong một danh sách task liền mạch', monthlyStats: 'Tổng số task trong tháng', weeklyStats: 'Tổng số task trong tuần',
          weekRange: '{{start}} – {{end}}',
          monthTotal: 'Tổng', monthCompleted: 'Hoàn thành', monthOpen: 'Đang mở', monthOverdue: 'Quá hạn',
          noTasksForMonth: 'Tháng này chưa có hoạt động task', noTasksForWeek: 'Tuần này chưa có hoạt động task', openTask: 'Mở {{title}}', due: 'Đến hạn', dueAt: 'Đến hạn {{time}}', added: 'Đã thêm',
          openObsidian: 'Đưa sang Obsidian', obsidianOpening: 'Đang chuẩn bị ghi chú…',
          obsidianHint: 'Tạo ghi chú Markdown trong Obsidian. Không cần cài plugin.',
          obsidianNeedsSetup: 'Hãy chọn vault local và thư mục đích trước khi đưa tổng kết tháng sang Obsidian.',
          obsidianDestination: 'Nơi lưu: {{vault}} / {{path}}', configureObsidian: 'Cấu hình Obsidian',
          obsidianReady: 'Markdown đã sẵn sàng và Obsidian đang được mở.', obsidianError: 'Không mở được Obsidian.',
          obsidianNoteName: 'Tổng kết Mindoist {{month}}', obsidianNoteTitle: 'Tổng kết tháng trên Mindoist — {{month}}',
          obsidianWeeklyNoteTitle: 'Tổng kết tuần trên Mindoist — {{range}}',
          monthlyDigest: '{{total}} task · {{completed}} hoàn thành · {{open}} đang mở · {{overdue}} quá hạn', weeklyDigest: '{{total}} task trong tuần · {{completed}} hoàn thành · {{open}} đang mở · {{overdue}} quá hạn',
          previewMarkdown: 'Xem trước Markdown', hideMarkdown: 'Ẩn bản xem trước', markdownPreviewTitle: 'Template Markdown cho Obsidian',
          markdownPreviewHint: 'Đây là chính xác phần frontmatter và checkbox sẽ được tạo cho kỳ đang chọn.', copyMarkdown: 'Sao chép Markdown',
          markdownCopied: 'Đã sao chép Markdown.', markdownCopyError: 'Không sao chép được Markdown.', previousWeek: 'Tuần trước', nextWeek: 'Tuần sau',
          previousMonth: 'Tháng trước', nextMonth: 'Tháng sau', calendarDay: '{{date}}, {{count}} task',
          taskCount: '{{count}} task', noTasksForDate: 'Không có task trong ngày này',
        },
        repeatBadge: 'Lặp lại',
        settingsPage: {
          title: 'Cài đặt', account: 'Tài khoản', appearance: 'Giao diện', navigation: 'Điều hướng', integrations: 'Tích hợp', google: 'Google', data: 'Dữ liệu', about: 'Giới thiệu',
          integrationsHint: 'Kết nối các dịch vụ tin cậy với tài khoản Mindoist của bạn.',
          obsidianTitle: 'Obsidian', obsidianDescription: 'Đưa tổng kết mỗi tháng thành note Markdown trong vault local mà không cần cài plugin.',
          obsidianConfigured: 'Đã cấu hình', obsidianNotConfigured: 'Chưa cấu hình',
          obsidianVault: 'Tên hoặc ID vault', obsidianVaultHint: 'Dùng tên hiện trong Obsidian, ví dụ “Hiếu - Personal”, hoặc ID vault gồm 16 ký tự.',
          obsidianFolder: 'Thư mục bên trong vault', obsidianFolderHint: 'Nhập đường dẫn tính từ gốc vault. Để trống nếu muốn dùng thư mục note mặc định.',
          obsidianFilename: 'Tên note theo tháng', obsidianFilenameHint: 'Giữ {{monthToken}} trong tên để mỗi tháng có một note riêng.',
          obsidianWeeklyFilename: 'Tên note theo tuần', obsidianWeeklyFilenameHint: 'Giữ {{weekToken}} trong tên để mỗi tuần có một note riêng.',
          obsidianPreview: 'Xem trước nơi lưu', obsidianMonthlyShort: 'Tháng', obsidianWeeklyShort: 'Tuần', obsidianVaultPlaceholder: 'Vault của bạn',
          obsidianLocalOnly: 'Cấu hình này chỉ được lưu trong trình duyệt hiện tại cho tài khoản Mindoist đang đăng nhập.',
          obsidianOpenVault: 'Mở thử vault', obsidianSave: 'Lưu cấu hình Obsidian', obsidianSaved: 'Đã lưu',
          obsidianErrors: {
            vaultRequired: 'Hãy nhập tên hoặc ID vault Obsidian.', folderInvalid: 'Đường dẫn thư mục phải nằm trong vault, không chứa .. hoặc ký tự tên file không hợp lệ.',
            filenameRequired: 'Hãy nhập tên note theo tháng.', filenameMonthRequired: 'Hãy giữ {{monthToken}} để note của các tháng không trùng nhau.',
            filenameInvalid: 'Tên note không được chứa dấu gạch chéo hoặc ký tự tên file không hợp lệ.',
            weeklyFilenameRequired: 'Hãy nhập tên note theo tuần.', weeklyFilenameWeekRequired: 'Hãy giữ {{weekToken}} để note của các tuần không trùng nhau.',
            weeklyFilenameInvalid: 'Tên note tuần không được chứa dấu gạch chéo hoặc ký tự tên file không hợp lệ.',
          },
          theme: 'Chủ đề sáng/tối', language: 'Ngôn ngữ', googleCalendar: 'Google Calendar',
          password: 'Mật khẩu', passwordHint: 'Đặt hoặc đổi mật khẩu để đăng nhập bằng email.',
          newPassword: 'Mật khẩu mới', confirmPassword: 'Xác nhận mật khẩu', savePassword: 'Lưu mật khẩu',
          passwordMinError: 'Mật khẩu phải có ít nhất 6 ký tự.',
          passwordMismatch: 'Hai mật khẩu không khớp.', passwordSaved: 'Đã lưu mật khẩu.',
          googleCalendarHint: 'Đồng bộ các task có hạn với Google Calendar.',
          importTitle: 'Nhập dữ liệu', importHint: 'Nhập task từ app khác hoặc file CSV.',
          productivity: 'Năng suất',
          notifications: 'Nhắc nhở task',
          notificationsHint: 'Cho phép thông báo trình duyệt để nhắc nhở hiện ra khi đến giờ.',
          notificationsUnsupported: 'Trình duyệt hoặc chế độ app hiện tại chưa hỗ trợ push notification.',
          notificationsDenied: 'Thông báo đang bị chặn trong trình duyệt. Hãy bật trong cài đặt site để dùng nhắc nhở.',
          notificationsError: 'Không thể cập nhật thông báo. Hãy thử lại.',
          pomodoroWorkMinutes: 'Thời gian tập trung',
          pomodoroBreakMinutes: 'Thời gian nghỉ',
          pomodoroWorkMinutesHint: 'Phút mỗi phiên tập trung (1–120)',
          pomodoroBreakMinutesHint: 'Phút mỗi lần nghỉ (1–60)',
          workHoursPerDay: 'Số giờ làm việc mỗi ngày',
          workHoursPerDayHint: 'Dùng cho thanh tiến độ lên kế hoạch Today (1–24)',
          telegramBot: 'Mindoist trên Telegram', telegramHint: 'Dùng bot chung của Mindoist.',
          telegramConnected: 'Đã kết nối', telegramPending: 'Đang chờ xác nhận',
          telegramLoading: 'Đang kiểm tra kết nối Telegram…', telegramUnavailable: 'Telegram chưa được cấu hình.',
          telegramUnlinked: 'Kết nối tài khoản Telegram của bạn để tiếp tục.',
          telegramPendingHint: 'Mở bot và bấm Start để xác nhận tài khoản này.',
          telegramExpires: 'Liên kết này hết hạn lúc {{time}}.', telegramAccount: 'Tài khoản Telegram',
          telegramLinkedAt: 'Đã liên kết {{date}}', telegramConnect: 'Kết nối Telegram',
          telegramCreating: 'Đang tạo liên kết…', telegramNewLink: 'Tạo liên kết mới', telegramOpen: 'Mở Telegram',
          telegramDisconnect: 'Ngắt kết nối', telegramDisconnecting: 'Đang ngắt…',
          telegramDisconnectConfirm: 'Ngắt kết nối Telegram?', telegramLoadError: 'Không kiểm tra được Telegram.', telegramRetry: 'Thử lại',
          telegramConnectError: 'Không tạo được liên kết Telegram.', telegramDisconnectError: 'Không ngắt được Telegram.',
          telegramGuideTitle: 'Cách dùng Mindoist trên Telegram', telegramGuideHint: 'Cứ nhắn tự nhiên.',
          telegramGuideStep1Title: 'Kết nối một lần', telegramGuideStep1Text: 'Mở bot và bấm Start.',
          telegramGuideStep2Title: 'Gửi yêu cầu', telegramGuideStep2Text: 'Ghi các chi tiết bạn cần.',
          telegramGuideStep3Title: 'Kiểm tra bản nháp', telegramGuideStep3Text: 'Trả lời xác nhận, sửa hoặc hủy.',
          telegramGuideGoalColumn: 'Bạn muốn làm gì', telegramGuideMessageColumn: 'Tin nhắn ví dụ',
          telegramGuideCreateLabel: 'Tạo công việc', telegramGuideCreateExample: 'Tạo công việc “Gia hạn domain” trong dự án Công việc',
          telegramGuideBatchLabel: 'Tạo nhiều công việc', telegramGuideBatchExample: 'Tạo thẻ #HạTầng rồi tạo: 1. Kiểm tra DNS; 2. Gia hạn SSL',
          telegramGuideTodayLabel: 'Xem theo ngày', telegramGuideTodayExample: 'Hôm nay tôi có những công việc gì?',
          telegramGuideStatsLabel: 'Xem thống kê', telegramGuideStatsExample: 'Thống kê công việc tuần này',
          telegramGuideReviseLabel: 'Sửa hoặc hủy', telegramGuideReviseExample: 'sửa hạn thành 14:00 · hủy',
          telegramGuideNote: 'Hãy ghi đúng tên dự án và thẻ đã có trong Mindoist. Với yêu cầu tạo công việc, dữ liệu chỉ được lưu sau khi bạn trả lời xác nhận.',
        },
        notificationPrompt: {
          title: 'Bật cảnh báo nhé?',
          description: 'Mindoist có thể báo khi task và countdown tới hạn.',
          enable: 'Bật thông báo',
          enabling: 'Đang bật…',
          later: 'Để sau',
          dismiss: 'Đóng lời nhắc bật thông báo',
          error: 'Chưa bật được thông báo. Hãy thử lại.',
        },
        countdown: {
          add: 'Thêm ngày đếm', title: 'Tiêu đề', titlePlaceholder: 'Sinh nhật, kỷ niệm, deadline...',
          date: 'Ngày', time: 'Giờ (không bắt buộc)', color: 'Màu', save: 'Lưu', delete: 'Xóa ngày đếm',
          empty: 'Chưa có ngày đếm nào — thêm một mốc thời gian đáng nhớ.',
          daysLeft: 'ngày nữa', daysAgo: 'ngày trước',
          reminder: 'Nhắc nhở', reminderNone: 'Chỉ đúng ngày',
          reminderDays_one: 'Báo trước {{count}} ngày', reminderDays_other: 'Báo trước {{count}} ngày',
          showInCalendar: 'Hiện trên Lịch',
          showInCalendarHint: 'Hiện thêm ngày đếm này như 1 sự kiện đúng ngày trên trang Lịch.',
        },
      },
    },
  },
  interpolation: {
    escapeValue: false,
  },
});

export default i18n;
