import { sql } from './db.ts';
import { json } from './http.ts';
import { requireAuth } from './sf0.ts';

type Row = Record<string, unknown>;
const providers = new Set(['GEMINI', 'ANTHROPIC', 'OPENAI', 'OPENROUTER', 'OPENAI_COMPATIBLE']);

function bad(message: string, status = 400) { return json({ success: false, error: message }, { status }); }
function bodyOf(request: Request): Promise<Record<string, unknown>> { return request.json().catch(() => ({})).then(value => value && typeof value === 'object' ? value as Record<string, unknown> : {}); }
function isHttps(value: unknown) { if (value === null || value === undefined || value === '') return true; try { const url = new URL(String(value)); return url.protocol === 'https:' && !url.username && !url.password; } catch { return false; } }
function joinUrl(base: string, path: string) { return `${base.replace(/\/$/, '')}/${path.replace(/^\//, '')}`; }
async function testProvider(input: { provider: string; model: string; apiBase?: string | null; apiKey: string; requestTimeoutMs: number }) {
  const startedAt = Date.now(); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), Math.max(1000, Math.min(120000, input.requestTimeoutMs || 30000)));
  try {
    let url = ''; let headers: Record<string, string> = { 'content-type': 'application/json' }; let payload: unknown;
    if (input.provider === 'GEMINI') {
      url = `${joinUrl(input.apiBase || 'https://generativelanguage.googleapis.com/v1beta', `models/${encodeURIComponent(input.model)}:generateContent`)}?key=${encodeURIComponent(input.apiKey)}`;
      payload = { contents: [{ parts: [{ text: 'Reply with OK.' }] }], generationConfig: { maxOutputTokens: 1 } };
    } else if (input.provider === 'ANTHROPIC') {
      url = joinUrl(input.apiBase || 'https://api.anthropic.com', '/v1/messages'); headers = { ...headers, 'x-api-key': input.apiKey, 'anthropic-version': '2023-06-01' };
      payload = { model: input.model, max_tokens: 1, messages: [{ role: 'user', content: 'Reply with OK.' }] };
    } else {
      url = joinUrl(input.apiBase || (input.provider === 'OPENROUTER' ? 'https://openrouter.ai/api/v1' : 'https://api.openai.com/v1'), '/chat/completions'); headers = { ...headers, authorization: `Bearer ${input.apiKey}` };
      payload = { model: input.model, max_tokens: 1, messages: [{ role: 'user', content: 'Reply with OK.' }] };
    }
    const response = await fetch(url, { method: 'POST', headers, body: JSON.stringify(payload), signal: controller.signal }); const latencyMs = Math.max(0, Date.now() - startedAt);
    if (!response.ok) return { ok: false as const, status: response.status, latencyMs, message: `Provider returned HTTP ${response.status}` };
    return { ok: true as const, status: response.status, latencyMs, message: 'Connection successful' };
  } catch (error) {
    const latencyMs = Math.max(0, Date.now() - startedAt); const timeout = error instanceof Error && error.name === 'AbortError';
    return { ok: false as const, latencyMs, message: timeout ? 'Provider request timed out' : 'Provider connection failed' };
  } finally { clearTimeout(timer); }
}
function hint(value: string) { return `••••${value.slice(-4)}`; }
function rootSecret() { const value = Deno.env.get('JWT_SECRET') || ''; if (value.length < 32) throw new Error('Provider encryption requires a root secret of at least 32 characters'); return value; }
async function key() { const material = await crypto.subtle.importKey('raw', new TextEncoder().encode(rootSecret()), 'HKDF', false, ['deriveKey']); return crypto.subtle.deriveKey({ name: 'HKDF', hash: 'SHA-256', salt: new TextEncoder().encode('mindoist-admin-control-plane'), info: new TextEncoder().encode('mindoist/provider-api-keys/v1') }, material, { name: 'AES-GCM', length: 256 }, false, ['encrypt', 'decrypt']); }
async function encrypt(value: string) { const nonce = crypto.getRandomValues(new Uint8Array(12)); const encrypted = new Uint8Array(await crypto.subtle.encrypt({ name: 'AES-GCM', iv: nonce, additionalData: new TextEncoder().encode('mindoist/provider-api-keys/v1') }, await key(), new TextEncoder().encode(value))); const tag = encrypted.slice(-16); const ciphertext = encrypted.slice(0, -16); return ['v1', btoa(String.fromCharCode(...nonce)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,''), btoa(String.fromCharCode(...tag)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,''), btoa(String.fromCharCode(...ciphertext)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')].join('.'); }
async function decrypt(value: string) { const parts = value.split('.'); if (parts.length !== 4 || parts[0] !== 'v1') throw new Error('Unable to decrypt provider secret'); const decode = (part: string) => { const raw = atob(part.replace(/-/g,'+').replace(/_/g,'/') + '='.repeat((4-part.length%4)%4)); return Uint8Array.from(raw, char => char.charCodeAt(0)); }; const nonce=decode(parts[1]); const tag=decode(parts[2]); const cipher=decode(parts[3]); const merged=new Uint8Array(cipher.length+tag.length); merged.set(cipher); merged.set(tag,cipher.length); const plain=await crypto.subtle.decrypt({ name:'AES-GCM',iv:nonce,additionalData:new TextEncoder().encode('mindoist/provider-api-keys/v1') },await key(),merged); return new TextDecoder().decode(plain); }
function dto(row: Row) { return { id: row.id, label: row.label, provider: row.provider, model: row.model, apiBase: row.api_base ?? row.apiBase, enabled: row.enabled, priority: row.priority, requestTimeoutMs: row.request_timeout_ms ?? row.requestTimeoutMs, hasApiKey: true, apiKeyHint: row.api_key_hint ?? row.apiKeyHint, lastTestStatus: row.last_test_status ?? row.lastTestStatus, lastTestedAt: row.last_tested_at ?? row.lastTestedAt, lastTestLatencyMs: row.last_test_latency_ms ?? row.lastTestLatencyMs, lastTestHttpStatus: row.last_test_http_status ?? row.lastTestHttpStatus, lastTestError: row.last_test_error ?? row.lastTestError, createdAt: row.created_at ?? row.createdAt, updatedAt: row.updated_at ?? row.updatedAt }; }
async function admin(request: Request) { const auth = await requireAuth(request); if (auth instanceof Response) return auth; return auth.user.role === 'ADMIN' ? auth.user : json({ success: false, error: 'Admin access required' }, { status: 403 }); }

export async function routeAdmin(path: string, request: Request): Promise<Response | null> {
  if (path === '/internal/agent/ai-config' && request.method === 'GET') {
    const header = request.headers.get('authorization')?.replace(/^Bearer\s+/, ''); const expected = Deno.env.get('MINDOIST_AGENT_TOKEN');
    if (!expected || !header || header !== expected) return bad('Invalid agent token', 401);
    const rows = await sql<Row[]>`select id,label,provider,model,api_base as "apiBase",priority,request_timeout_ms as "requestTimeoutMs",encrypted_api_key as "encryptedApiKey" from ai_provider_configs where enabled=true order by priority asc,created_at asc`;
    const projected = []; for (const row of rows) { try { projected.push({ id: row.id, label: row.label, provider: row.provider, model: row.model, apiBase: row.apiBase, priority: row.priority, requestTimeoutMs: row.requestTimeoutMs, apiKey: await decrypt(String(row.encryptedApiKey)) }); } catch { /* skip corrupt secret */ } }
    const revisionBytes = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(JSON.stringify(projected))); const revision = Array.from(new Uint8Array(revisionBytes), byte => byte.toString(16).padStart(2,'0')).join('');
    return json({ success: true, data: { revision, providers: projected } });
  }
  if (!path.startsWith('/admin/')) return null;
  const current = await admin(request); if (current instanceof Response) return current;
  if (path === '/admin/overview' && request.method === 'GET') {
    const [[users], [active], [suspended], [allProviders], [enabled], [telegram]] = await Promise.all([
      sql<{ count: number }[]>`select count(*)::int as count from users`, sql<{ count: number }[]>`select count(*)::int as count from users where status='ACTIVE'::"UserStatus"`, sql<{ count: number }[]>`select count(*)::int as count from users where status='SUSPENDED'::"UserStatus"`, sql<{ count: number }[]>`select count(*)::int as count from ai_provider_configs`, sql<{ count: number }[]>`select count(*)::int as count from ai_provider_configs where enabled=true`, sql<{ count: number }[]>`select count(*)::int as count from telegram_connections`,
    ]); return json({ success: true, data: { users: users.count, activeUsers: active.count, suspendedUsers: suspended.count, providers: allProviders.count, enabledProviders: enabled.count, telegramConnections: telegram.count } });
  }
  if (path === '/admin/users' && request.method === 'GET') {
    const params = new URL(request.url).searchParams; const q = (params.get('q') || '').trim(); const offset = Math.max(0, Number(params.get('offset') || 0) || 0); const limit = Math.min(100, Math.max(1, Number(params.get('limit') || 50) || 50)); const term = `%${q}%`;
    const items = await sql<Row[]>`select u.id,u.email,u.name,u.role,u.status,u.time_zone as "timeZone",u.onboarding_required as "onboardingRequired",u.created_at as "createdAt",tc.telegram_username as "telegramUsername",tc.linked_at as "telegramLinkedAt" from users u left join telegram_connections tc on tc.user_id=u.id where (${q}='' or u.email ilike ${term} or u.name ilike ${term}) order by u.created_at desc offset ${offset} limit ${limit}`;
    const total = await sql<{ count: number }[]>`select count(*)::int as count from users where (${q}='' or email ilike ${term} or name ilike ${term})`; return json({ success: true, data: { items: items.map(row => ({ ...row, createdAt: row.createdAt instanceof Date ? row.createdAt.toISOString() : row.createdAt, telegramConnection: row.telegramUsername ? { telegramUsername: row.telegramUsername, linkedAt: row.telegramLinkedAt } : null })), total: total[0].count } });
  }
  const userMatch = path.match(/^\/admin\/users\/([^/]+)(?:\/revoke-sessions)?$/);
  if (userMatch && path.endsWith('/revoke-sessions') && request.method === 'POST') { if (!(await sql`select id from users where id=${userMatch[1]} limit 1`)[0]) return bad('User not found',404); await sql`delete from refresh_tokens where user_id=${userMatch[1]}`; await sql`insert into admin_audit_logs (id,actor_user_id,action,entity_type,entity_id,created_at) values (${crypto.randomUUID()},${current.id},'user.sessions_revoked','user',${userMatch[1]},now())`; return json({ success: true }); }
  if (userMatch && request.method === 'PATCH') {
    const input = await bodyOf(request); if ((input.role !== undefined && !['USER','ADMIN'].includes(String(input.role))) || (input.status !== undefined && !['ACTIVE','SUSPENDED'].includes(String(input.status))) || (input.role === undefined && input.status === undefined)) return bad('Invalid user update');
    if (userMatch[1] === current.id && input.role === 'USER') return bad('You cannot remove your own administrator role',409); if (userMatch[1] === current.id && input.status === 'SUSPENDED') return bad('You cannot suspend your own account',409);
    const target = await sql<Row[]>`select id,role,status from users where id=${userMatch[1]} limit 1`; if (!target[0]) return bad('User not found',404); if (target[0].role === 'ADMIN' && target[0].status === 'ACTIVE' && (input.role === 'USER' || input.status === 'SUSPENDED')) { const count=await sql<{count:number}[]>`select count(*)::int as count from users where role='ADMIN'::"UserRole" and status='ACTIVE'::"UserStatus"`; if (count[0].count<=1) return bad('At least one active administrator is required',409); }
    const rows = await sql<Row[]>`update users set role=coalesce(${input.role ?? null}::"UserRole",role),status=coalesce(${input.status ?? null}::"UserStatus",status),updated_at=now() where id=${userMatch[1]} returning id,email,name,role,status`; return json({ success:true,data:rows[0] });
  }
  if (path === '/admin/providers' && request.method === 'GET') { const rows=await sql<Row[]>`select * from ai_provider_configs order by priority asc,created_at asc`; return json({success:true,data:rows.map(dto)}); }
  if (path === '/admin/providers' && request.method === 'POST') {
    const input=await bodyOf(request); if (typeof input.label!=='string'||!input.label.trim()||input.label.length>80||typeof input.model!=='string'||!input.model.trim()||input.model.length>160||!providers.has(String(input.provider))||(String(input.provider)==='OPENAI_COMPATIBLE'&&!input.apiBase)||(input.enabled!==undefined&&typeof input.enabled!=='boolean')||(input.priority!==undefined&&(!Number.isInteger(input.priority)||Number(input.priority)<1||Number(input.priority)>10000))||(input.requestTimeoutMs!==undefined&&(!Number.isInteger(input.requestTimeoutMs)||Number(input.requestTimeoutMs)<1000||Number(input.requestTimeoutMs)>120000))||typeof input.apiKey!=='string'||input.apiKey.length<8||input.apiKey.length>4096||!isHttps(input.apiBase)) return bad('Invalid provider configuration');
    if (input.enabled !== false && (await sql<{count:number}[]>`select count(*)::int as count from ai_provider_configs where enabled=true`)[0].count>=6) return bad('At most six AI providers can be enabled',409);
    const rows=await sql<Row[]>`insert into ai_provider_configs (id,label,provider,model,api_base,encrypted_api_key,api_key_hint,enabled,priority,request_timeout_ms,created_at,updated_at) values (${crypto.randomUUID()},${input.label.trim()},${input.provider}::"AiProviderType",${input.model.trim()},${input.apiBase??null},${await encrypt(String(input.apiKey))},${hint(String(input.apiKey))},${input.enabled!==false},${Number(input.priority)||100},${Number(input.requestTimeoutMs)||30000},now(),now()) returning *`; await sql`insert into admin_audit_logs (id,actor_user_id,action,entity_type,entity_id,metadata,created_at) values (${crypto.randomUUID()},${current.id},'provider.created','ai_provider',${rows[0].id},${JSON.stringify({provider:input.provider,model:input.model})},now())`; return json({success:true,data:dto(rows[0])},{status:201});
  }
  const providerTestMatch=path.match(/^\/admin\/providers\/([^/]+)\/test$/); if(providerTestMatch && request.method==='POST'){const provider=(await sql<Row[]>`select * from ai_provider_configs where id=${providerTestMatch[1]} limit 1`)[0];if(!provider)return bad('Provider not found',404);let result:{ok:boolean;status?:number;latencyMs:number;message:string};try{result=await testProvider({provider:String(provider.provider),model:String(provider.model),apiBase:provider.api_base as string|null,apiKey:await decrypt(String(provider.encrypted_api_key)),requestTimeoutMs:Number(provider.request_timeout_ms)||30000});}catch{result={ok:false,latencyMs:0,message:'Provider connection failed'};}const testedAt=new Date();await sql`update ai_provider_configs set last_test_status=${result.ok?'HEALTHY':'FAILED'},last_tested_at=${testedAt},last_test_latency_ms=${result.latencyMs},last_test_http_status=${result.status??null},last_test_error=${result.ok?null:result.message},updated_at=now() where id=${provider.id}`;await sql`insert into admin_audit_logs (id,actor_user_id,action,entity_type,entity_id,metadata,created_at) values (${crypto.randomUUID()},${current.id},'provider.tested','ai_provider',${provider.id},${JSON.stringify({ok:result.ok,status:result.status??undefined})},now())`;return json({success:result.ok,data:{...result,testedAt:testedAt.toISOString()},error:result.ok?undefined:result.message},{status:result.ok?200:502});}
  const providerMatch=path.match(/^\/admin\/providers\/([^/]+)$/); if(providerMatch && request.method==='DELETE'){const row=await sql<Row[]>`select * from ai_provider_configs where id=${providerMatch[1]} limit 1`;if(!row[0])return bad('Provider not found',404);if(row[0].enabled&&(await sql<{count:number}[]>`select count(*)::int as count from ai_provider_configs where enabled=true`)[0].count<=1)return bad('At least one AI provider must remain enabled',409);await sql`delete from ai_provider_configs where id=${providerMatch[1]}`;return json({success:true});}
  if(providerMatch && request.method==='PATCH'){const input=await bodyOf(request);const currentProvider=(await sql<Row[]>`select * from ai_provider_configs where id=${providerMatch[1]} limit 1`)[0];if(!currentProvider)return bad('Provider not found',404);const nextProvider=String(input.provider??currentProvider.provider);const nextBase=input.apiBase===undefined?(currentProvider.api_base as string|null):input.apiBase;if((input.label!==undefined&& (typeof input.label!=='string'||!input.label.trim()||input.label.length>80))||(input.model!==undefined&&(typeof input.model!=='string'||!input.model.trim()||input.model.length>160))||(input.enabled!==undefined&&typeof input.enabled!=='boolean')||(input.priority!==undefined&&(!Number.isInteger(input.priority)||Number(input.priority)<1||Number(input.priority)>10000))||(input.requestTimeoutMs!==undefined&&(!Number.isInteger(input.requestTimeoutMs)||Number(input.requestTimeoutMs)<1000||Number(input.requestTimeoutMs)>120000))||!providers.has(nextProvider)||((nextProvider==='OPENAI_COMPATIBLE')&&!nextBase)||!isHttps(nextBase))return bad('Invalid provider configuration');if(input.apiKey!==undefined&&(!input.apiKey||String(input.apiKey).length<8||String(input.apiKey).length>4096))return bad('Invalid provider configuration');const fields:Array<[string,unknown]>=[];for(const [key,col] of [['label','label'],['model','model'],['apiBase','api_base'],['enabled','enabled'],['priority','priority'],['requestTimeoutMs','request_timeout_ms']] as const)if(input[key]!==undefined)fields.push([col,input[key]===null?null:input[key]]);if(input.provider!==undefined)fields.push(['provider',input.provider]);if(input.apiKey){fields.push(['encrypted_api_key',await encrypt(String(input.apiKey))]);fields.push(['api_key_hint',hint(String(input.apiKey))]);}if(fields.length){const fragments=fields.map(([col,val]) => col === 'provider' ? sql`provider=${val}::"AiProviderType"` : sql`${sql(col)}=${val}`);let joined=fragments[0];for(let index=1;index<fragments.length;index++)joined=sql`${joined},${fragments[index]}`;const rows=await sql<Row[]>`update ai_provider_configs set ${joined},updated_at=now() where id=${providerMatch[1]} returning *`;return json({success:true,data:dto(rows[0])});}return json({success:true,data:dto(currentProvider)});}
  if(path==='/admin/audit'&&request.method==='GET'){const rows=await sql<Row[]>`select a.*,u.name as "actorName",u.email as "actorEmail" from admin_audit_logs a left join users u on u.id=a.actor_user_id order by a.created_at desc limit 100`;return json({success:true,data:rows});}
  return bad('Method not allowed',405);
}
